
#Enable or Disable Difficulty Increasing Multipliers. True is activated, False is deactivated
["Difficulty Increasing multiplier"]
	#We all get old at some point. Upon breeding a finite number of times, animals and villagers will die of old age.
	agingMultiplier = false
	#When you take damage, your ability to heal is nullified until you hit a monster or a player with a melee attack. Punch 'em in the chin!
	blackEyeMultiplier = false
	#Bombs away! Creepers always explode on death, regardless of method.
	cannonMultiplier = false
	#Phantoms are a lame punishment for lack of sleep. Enjoy debuffs and eventual death by lack of sleep with this modifier!
	fatigueMultiplier = true
	#There is a chance any animal usually farmed for food will explode violently when a player hits them. Tread Lightly.
	karmicJusticeMultiplier = false
	#!!!Temporarily Disabled in Code!!! Fighting the same zombies gets old. Zombies are converted to drowned, husks, or zombie villagers instantly, skeletons are converted to strays instantly, and creepers are always supercharged.
	shiftMultiplier = false
	#Your particularly soft skin makes you more vulnerable to damage. All incoming damage has an extra added to it.
	softSkinMultiplier = false
	#Cave spiders inflict poison for a brief moment on easy, and both wither and poison on normal and hard. Spiders also get the ability to poison you for a shorter amount of time.
	venomMultiplier = true
	#All hostile mobs have increased health
	hardenedMultiplier = true
	#Pillagers, Skeletons, Strays, and Witches all have significantly sped up attack rates.
	angerMultiplier = true
	#Creeper explosions and Ghast fireballs have a larger explosion radius. For all your mass terrain destruction needs.
	unstableMultiplier = false
	#Entities on fire will stay on fire until water is applied (or they have died)
	flammableMultiplier = false
	#Eating meat makes you feel sick to your stomach. Whether or not it's for moral reasons, health reasons, or anything in between.
	vegetarianMultiplier = false
	#That's just... Wrong - Some neutral mobs may have more aggression towards you.
	wrongMultiplier = true
	#Burn! BURN! BUUURRRRN! - Fire damage does significantly more damage.
	infernoMultiplier = false
	#Bees will explode violently upon stinging.
	eruptiveSwarmMultiplier = false

#Enabled or Disable Difficulty Decreasing Multipliers. True is activated, False is deactivated
["Difficulty Decreasing multiplier"]
	#Future technology embedded into your skin allows you to store up kinetic energy from attacks to release on your foes on your next attack, adding up to 50 hearts of damage maximum.
	KineticMultiplier = false
	#When you are about to die, you're instantly brought back to full health. Allows you to get back into the fight immediately, but does still increase your death counters.
	undyingMultiplier = false
	#Modern furnaces can get more mileage out of fuel.
	fuelEfficientMultiplier = false
	#Stronger understanding of proper anvil usage makes you less likely to damage it.
	blacksmithingMultiplier = false
	#Tools may be replaced when they are destroyed.
	warrantyMultiplier = false
	#Npc villagers may celebrate on any given day
	celebrationMultiplier = false
	#Resting works wonders to heal you...
	restedMultiplier = false
	#Your attacks cause a surge of uncontrollable magic to manifest.. for better or worse.
	wildMultiplier = false

#Exterior multipliers. May be increasing or decreasing. All of these are dependent on mods for registering.
["Exterior Difficulty multiplier"]
	#All living entities that harm you have a chance to infect you with Immortuos Calyx, even if they aren't infected themselves
	pandemicMultiplier = false

#Additional Multiplier modifications. Want to make multipliers stronger or weaker? Here's where you can do it.
["Custom Multiplier Values"]
	#The amount of times a creature can breed before dying of old age with the aging multiplier enabled
	#Range: > 1
	maximumAge = 4
	#The health multiplier given to monsters when spawned while Hardened is enabled
	#Range: 1.0 ~ 2.147483647E9
	hardenedBoost = 1.5
	#The multiplier given to damage taken by players when SoftSkin is enabled
	#Range: 1.0 ~ 2.147483647E9
	softskinBoost = 1.5
	#Explosion size of creepers and ghast fireballs when Unstable is enabled
	#Range: > 1
	unstableExplosive = 5
	#Explosion size of bees when Eruptive Swarm is enabled
	#Range: > 1
	eruptiveSwarm = 4
	#1 in X chance that a valid neutral mob will be effected by wrong when it is enabled.
	#Range: > 1
	wrongChance = 30
	#1 in X chance that a valid passive mob will be effected by karmic justice when it is enabled.
	#Range: > 1
	karmicJusticeChance = 20
	#Fuel efficiency multiplier when fuel efficient is enabled
	#Range: > 1
	fuelEfficiencyMultiplier = 4
	#1 in X chance that an attack will invoke a wild effect when Wild is enabled.
	#Range: > 1
	wildMagicChance = 6
	#1 in X chance during the day to activate a celebration when it is enabled
	#Range: > 1
	celebrationChance = 9
	#Percent chance, divided by 100, that a player damages an anvil with blacksmithing on.
	#Range: 0.0 ~ 1.0
	blacksmithingChange = 0.06

